platform:
  - Win32
build: off
environment:
    PYTHON: "C:\\Python35"
    matrix:  
        - TYPE: zpm
        - TYPE: release
          ARCH: x86
          PLAT: Win32
          VSTUD: vs2015
        - TYPE: debug
          ARCH: x86
          PLAT: Win32
          VSTUD: vs2015
        - TYPE: release
          ARCH: x86_64
          PLAT: x64
          VSTUD: vs2015
        - TYPE: debug
          ARCH: x86_64
          PLAT: x64
          VSTUD: vs2015
        - TYPE: release
          ARCH: x86_64
          PLAT: x64
          VSTUD: vs2015
        - TYPE: release 
          ARCH: x86_64
          PLAT: x64
          VSTUD: vs2015
install:
    - powershell -command "Invoke-WebRequest -Uri https://raw.githubusercontent.com/Zefiros-Software/ZPM/features/refactor/script/install-zpm.bat -OutFile %TEMP%/install-zpm.bat" && %TEMP%/install-zpm.bat 
    - "SET PATH=%PATH%;%USERPROFILE%/zpm/bin"
test_script:
    - zpm run build-ci --verbose --skip-lock PlotLib plot
    - zpm run test-ci --verbose --skip-lock PlotLib plot