description: ''
keywords: []
website: 'http://plotlib.eu/'
license: MIT
authors:
  - name: Mick van Duijn
    email: m.vanduijn@zefiros.eu
    website: 'https://zefiros.eu/'
  - name: Paul Visscher
    email: p.e.visscher@zefiros.eu
    website: 'https://zefiros.eu/'
  - name: Koen Visscher
    email: k.m.visscher@zefiros.eu
    website: 'https://zefiros.eu/'
public:
  libraries:
    - name: Zefiros-Software/Armadillo
      optional: true
      version: '^7.800.0'
modules:
  - name: 'Zefiros-Software/Miniconda'
    version: '@head'
dev:
  modules:
    - name: Zefiros-Software/Zefiros-Defaults
      version: '@head'
  libraries:
    - name: Zefiros-Software/Armadillo
      optional: false
      version: '^7.800.0'
settings:
  headerOnly:
    default: false
    reduce: anyTrue
  useZPMPython:
    default: true
    reduce: anyFalse
