language: generic
cache:
    directories: 
        - $HOME/.cache/matplotlib
matrix:
    include:
        # Use the built in venv for linux builds
        - os: linux
          dist: trusty
        # Use generic language for osx
        - os: osx
          osx_image: xcode8
          language: generic
install:
    - wget -O - https://raw.githubusercontent.com/Zefiros-Software/ZPM/master/script/install-zpm-travis.sh | bash
    - chmod a+x ./script/travis-build.sh
    # annoying pip fix
    - export BOTO_CONFIG=/tmp/bogusvalue
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install g++-multilib -y; fi
script:
    - ./script/travis-build.sh